#!/usr/bin/make -f
#
# Makefile für alle Hilfsprogramme
#
# Frank Schütte
# 2016
# GPL v3
#

CURDIR=$(shell pwd)

include $(CURDIR)/common.mk

#URLS, SOURCES in common.mk

#BB_DIR in common.mk
CHNTPW_DIR=$(CURDIR)/$(firstword $(filter chntpw-%, $(SOURCES)))

MSSYS_DIR=$(CURDIR)/$(firstword $(filter ms-sys-%, $(SOURCES)))
BUILDMSSYS=$(BUILDDIR)/build-mssys

NTFS3G_DIR=$(CURDIR)/$(firstword $(filter ntfs-%, $(SOURCES)))
NTFS3G_BINS=src/ntfs-3g ntfsprogs/mkntfs ntfsprogs/ntfsclone ntfsprogs/ntfslabel ntfsprogs/ntfsresize

BUILDNTFS32=$(BUILDDIR)/build-ntfs32
BUILDNTFS64=$(BUILDDIR)/build-ntfs64

LSASECRETS_DIR=$(CURDIR)/$(firstword $(filter %-master, $(SOURCES)))

DIRS:=$(CACHEDIR) $(BB_DIR) $(BUILDBB32) $(BUILDBB64) $(CHNTPW_DIR) $(MSSYS_DIR) \
	$(NTFS3G_DIR) $(BUILDNTFS32) $(BUILDNTFS64) $(LSASECRETS_DIR)

# targets

all: build

$(DIRS):
	mkdir -p $(DIRS)

$(ARCHIVES): | $(DIRS)
	wget -nc --directory-prefix=$(CACHEDIR) $(URLS)
	cd $(CACHEDIR); $(foreach file, $(notdir $(ARCHIVES)),grep $(file) $(DEBIANDIR)/md5sums.src | md5sum -c ; )

$(SOURCES): | $(ARCHIVES)
	cd $(CURDIR); $(foreach archive, $(filter %.zip, $(ARCHIVES)), unzip -o $(archive);)
	cd $(CURDIR); $(foreach archive, $(filter-out %.zip, $(ARCHIVES)), tar xvf $(archive);)
	cd $(CURDIR)/$(filter busybox-%, $(SOURCES)); for i in $(PATCHDIR)/busybox/*; do patch -p1 <$$i; done
	touch $(addprefix $(CURDIR)/, $(SOURCES))

$(addsuffix /.config, $(BUILDBB32) $(BUILDBB64)): $(CONFDIR)/busybox.conf | $(BB_DIR)
	cp $(CONFDIR)/busybox.conf $(BUILDBB32)/.config
	cd $(BB_DIR); PATH=$(TOOLCHAIN):$(PATH) ARCH=i386 CFLAGS="$(CFLAGS) -m32 --sysroot=$(SYSROOT)" CROSS_COMPILE=i386-linux-gnu- make CONFIG_PREFIX=$(SYSROOT) O=$(BUILDBB32) oldconfig
	cp $(CONFDIR)/busybox.conf $(BUILDBB64)/.config
	cd $(BB_DIR); CFLAGS="$(CFLAGS) --sysroot=$(SYSROOT64)" make CONFIG_PREFIX=$(SYSROOT64) O=$(BUILDBB64) oldconfig

configure: $(SOURCES) $(addsuffix /.config, $(BUILDBB32) $(BUILDBB64))

build: build-busybox build-mssys build-chntpw build-ntfs

build-busybox: $(BUILDBB32)/busybox $(BUILDBB64)/busybox

$(BUILDBB32)/busybox $(BUILDBB64)/busybox: $(BUILDBB32)/.config $(BUILDBB64)/.config
	echo "[1mBuilding busybox...[0m"
	cd $(BUILDBB32);PATH=$(TOOLCHAIN):$(PATH) ARCH=i386 CFLAGS="$(CFLAGS) -m32 --sysroot=$(SYSROOT)" CROSS_COMPILE=i386-linux-gnu- make CONFIG_PREFIX=$(SYSROOT)
	echo "[1mBuilding 64bit busybox...[0m"
	cd $(BUILDBB64); CFLAGS="$(CFLAGS) --sysroot=$(SYSROOT64)" make CONFIG_PREFIX=$(SYSROOT64)

build-mssys: $(MSSYS_DIR)/bin/ms-sys

$(MSSYS_DIR)/bin/ms-sys: | $(MSSYS_DIR)
	echo "[1mBuilding ms-sys...[0m"
	cd $(MSSYS_DIR); PATH=$(TOOLCHAIN):$(PATH) CFLAGS="$(CFLAGS) -m32 --sysroot=$(SYSROOT)" \
			LDFLAGS="$(LDFLAGS) -m32 --sysroot=$(SYSROOT)" make
	strip $(MSSYS_DIR)/bin/ms-sys

build-chntpw: $(CHNTPW_DIR)/reged

$(CHNTPW_DIR)/reged: | $(CHNTPW_DIR)
	echo "[1mBuilding reged...[0m"
	cd $(CHNTPW_DIR); PATH=$(TOOLCHAIN):$(PATH) make reged;
	strip $(CHNTPW_DIR)/reged

build-ntfs: $(addprefix $(BUILDNTFS32)/, $(NTFS3G_BINS)) $(addprefix $(BUILDNTFS64)/, $(NTFS3G_BINS))

$(addprefix $(BUILDNTFS32)/, $(NTFS3G_BINS)): | $(NTFS3G_DIR)
	echo "[1mBuilding 32bit ntfs-3g...[0m"
	cd $(BUILDNTFS32); PATH=$(TOOLCHAIN):$(PATH) ARCH=i386 CFLAGS="$(CFLAGS) -m32 --sysroot=$(SYSROOT)" \
		$(NTFS3G_DIR)/configure --host=i386-linux-gnu --enable-really-static \
		--enable-xattr-mappings --enable-posix-acls
	cd $(BUILDNTFS32); PATH=$(TOOLCHAIN):$(PATH) ARCH=i386 CFLAGS="$(CFLAGS) -m32 --sysroot=$(SYSROOT)" make
	$(foreach bin, $(addprefix $(BUILDNTFS32)/, $(NTFS3G_BINS)), strip $(bin); )

$(addprefix $(BUILDNTFS64)/, $(NTFS3G_BINS)): | $(NTFS3G_DIR)
	echo "[1mBuilding 64bit ntfs-3g...[0m"
	cd $(BUILDNTFS64); CFLAGS="$(CFLAGS) --sysroot=$(SYSROOT64)" $(NTFS3G_DIR)/configure --enable-really-static \
		--enable-xattr-mappings --enable-posix-acls
	cd $(BUILDNTFS64); CFLAGS="$(CFLAGS) --sysroot=$(SYSROOT64)" make
	$(foreach bin, $(addprefix $(BUILDNTFS64)/, $(NTFS3G_BINS)), strip $(bin); )

distclean: clean

	rm -rf $(DIRS)

clean: 
	rm -rf $(filter build, $(DIRS))

install: $(CHNTPW_DIR)/reged $(MSSYS_DIR)/bin/ms-sys $(addsuffix /bin/busybox, $(SYSROOT) $(SYSROOT64)) \
	$(addprefix $(BUILDNTFS64)/, $(NTFS_BINS)) $(addprefix $(BUILDNTFS32)/, $(NTFS_BINS))
	$(foreach file, $(addprefix $(BUILDNTFS32)/, $(NTFS3G_BINS)), install -D -m 755 $(file) $(SYSROOT)/bin/$(notdir $(file)); )
	$(foreach file, $(addprefix $(BUILDNTFS64)/, $(NTFS3G_BINS)), install -D -m 755 $(file) $(SYSROOT64)/bin/$(notdir $(file)); )

$(addsuffix /bin/busybox, $(SYSROOT) $(SYSROOT64)): $(BUILDBB32)/busybox $(BUILDBB64)/busybox
	cd $(BUILDBB32); PATH=$(TOOLCHAIN):$(PATH) ARCH=i386 CFLAGS="$(CFLAGS) -m32 --sysroot=$(SYSROOT)" CROSS_COMPILE=i386-linux-gnu- make CONFIG_PREFIX=$(SYSROOT) install
	cd $(BUILDBB64); CFLAGS="$(CFLAGS) --sysroot=$(SYSROOT64)" make CONFIG_PREFIX=$(SYSROOT64) install

$(addsuffix /bin/ms-sys, $(SYSROOT) $(SYSROOT64)): $(MSSYS_DIR)/bin/ms-sys
	install -D -m 755 $(MSSYS_DIR)/bin/ms-sys $(SYSROOT)/bin/ms-sys
	install -D -m 755 $(MSSYS_DIR)/bin/ms-sys $(SYSROOT64)/bin/ms-sys

$(addsuffix /bin/reged, $(SYSROOT) $(SYSROOT64)):  $(CHNTPW_DIR)/reged
	install -D -m 755 $(CHNTPW_DIR)/reged $(SYSROOT)/bin/reged
	install -D -m 755 $(CHNTPW_DIR)/reged $(SYSROOT64)/bin/reged

.PHONY: all $(DIRS) distclean clean
.PHONY: configure
.PHONY: build build-busybox build-mssys build-chntpw build-ntfs
.PHONY: install
