#!/usr/bin/make -f#
# Frank Schütte
# 2016
# GPL v3
#

include common.mk

CURDIR=$(shell pwd)

BIN64_DEBS= libc6 libc6-dev libstdc++6 libstdc++-4.8-dev libgcc1 libgcc-4.8-dev \
	    libasan0 libatomic1 libgomp1 libitm1 libquadmath0 libtsan0 \
	    libudev1 libudev-dev libxkbcommon0 libxkbcommon-dev xkb-data \
	    libinput5 libinput-dev libevdev2 libevdev-dev libnih1 libnih-dev \
	    libnih-dbus1 libnih-dbus-dev libcgmanager0 libcgmanager-dev \
	    libdbus-1-3 libdbus-1-dev libmtdev1 libmtdev-dev \
	    mesa-common-dev \
	    pkg-config

#acl bc bluez bvi ctorrent dosfstools dropbear e2fsprogs efibootmgr \
#           ethtool gdisk grub-pc grub-pc-bin grub-common grub2-common \
#           grub-efi-ia32-bin kmod libc-bin libicu52 libgpod-common libmtp-runtime \
#           libnetpbm10 libparted0debian1 libpci3 libpng12-0 mount netpbm \
#           ncurses-bin parted pcmciautils reiserfsprogs rsync sysvinit-utils \
#           udev udisks udpcast util-linux uuid-dev uuid-runtime xserver-xorg-input-vmmouse \
#           zlib1g zlib1g-dev

BIN32_DEBS=acl bc bluez bvi ctorrent dosfstools dropbear e2fsprogs efibootmgr \
           ethtool gdisk grub-pc grub-pc-bin grub-common grub2-common \
           grub-efi-ia32-bin kmod libc-bin libicu52 libgpod-common libmtp-runtime \
           libnetpbm10 libparted0debian1 libpci3 libpng12-0 mount netpbm \
           ncurses-bin parted pcmciautils reiserfsprogs rsync sysvinit-utils \
           udev udisks udpcast util-linux uuid-dev uuid-runtime xserver-xorg-input-vmmouse \
           zlib1g zlib1g-dev

# targets

configure: configure32 configure64

configure32:
	# 32bit binaries
	echo "[1mInstalling 32bit headers...[0m"
	for i in $(BIN32_DEBS) ; do \
		pkg=`ls -1tr $(CACHEDIR)/$${i}_*_i386.deb 2>/dev/null | tail -1` ; \
		pkgall=`ls -1tr $(CACHEDIR)/$${i}_*_all.deb 2>/dev/null | tail -1` ; \
		if [ -z "$$pkg" -a -z "$$pkgall" ]; then \
			( cd $(CACHEDIR) ; echo "[1mDownloading $${i}:i386 ...[0m" ; apt-get download $${i}:i386 ) ; \
			rm -rf $(SYSROOT)/usr/share/doc/$$i ; \
		fi ; \
		if [ ! -d $(SYSROOT)/usr/share/doc/$$i ]; then \
			pkg=`ls -1tr $(CACHEDIR)/$${i}_*_i386.deb 2>/dev/null | tail -1` ; \
			if [ -z "$$pkg" ]; then \
			    pkg=`ls -1tr $(CACHEDIR)/$${i}_*_all.deb 2>/dev/null | tail -1` ; \
			fi ; \
			echo "[1mUnpacking $$pkg ...[0m" ; \
			dpkg -x $$pkg $(SYSROOT) ; \
		fi ; \
	done

configure64:
	# 64bit binaries
	echo "[1mInstalling 64bit headers...[0m"
	for i in $(BIN64_DEBS) ; do \
		pkg=`ls -1tr $(CACHEDIR)/$${i}_*_amd64.deb 2>/dev/null | tail -1` ; \
		pkgall=`ls -1tr $(CACHEDIR)/$${i}_*_all.deb 2>/dev/null | tail -1` ; \
		if [ -z "$$pkg" -a -z "$$pkgall" ]; then \
			( cd $(CACHEDIR) ; echo "[1mDownloading $${i}:amd64 ...[0m" ; apt-get download $${i}:amd64 ) ; \
			rm -rf $(SYSROOT64)/usr/share/doc/$$i ; \
		fi ; \
		if [ ! -d $(SYSROOT64)/usr/share/doc/$$i ]; then \
			pkg=`ls -1tr $(CACHEDIR)/$${i}_*_amd64.deb 2>/dev/null | tail -1` ; \
			if [ -z "$$pkg" ]; then \
			    pkg=`ls -1tr $(CACHEDIR)/$${i}_*_all.deb 2>/dev/null | tail -1` ; \
			fi ; \
			echo "[1mUnpacking $$pkg ...[0m" ; \
			dpkg -x $$pkg $(SYSROOT64) ; \
		fi ; \
	done

#config-dfb64: $(DIRECTFB)/configure
#	( cd $(DIRECTFB) ; PKG_CONFIG_LIBDIR=$(SYSROOT64)/usr/lib/pkgconfig \
#	PKG_CONFIG_PATH="" ACLOCAL_FLAGS="-I $(SYSROOT64)/usr/share/aclocal" \
#	CPPFLAGS=-I$(SYSROOT64)/usr/include LDFLAGS=-L$(SYSROOT64)/usr/lib \
#	./configure --prefix=$(SYSROOT64) $(DIRECTFB_OPTS) )

build:

distclean: clean

clean: 

install:

.PHONY: download build distclean clean install
.PHONY: configure configure32 configure64
