#!/usr/bin/make -f#
#
# Dieses Makefile installiert alle Binaries in die jeweiligen sysroot-Verzeichnisse.
# Frank Schütte
# 2016
# GPL v3
#

CURDIR=$(shell pwd)

include common.mk

ALL_DEBS  = xkb-data ncurses-base

BIN32_DEBS= grub-efi-ia32-bin

BIN64_DEBS= grub-efi-amd64-bin

BIN_DEBS  = cloop-utils gdisk libstdc++-4.8-dev \
	    libc6 libc6-dev libstdc++6 libgcc1 libgcc-4.8-dev \
	    libasan0 libatomic1 libgomp1 libitm1 libquadmath0 \
	    libudev1 libudev-dev libxkbcommon0 libxkbcommon-dev \
	    libevdev2 libevdev-dev libnih1 libnih-dev \
	    libnih-dbus1 libnih-dbus-dev libcgmanager0 libcgmanager-dev \
	    libdbus-1-3 libdbus-1-dev libmtdev1 libmtdev-dev \
	    mesa-common-dev pkg-config libuuid1 \
	    acl bc bluez bvi ctorrent dosfstools dropbear e2fsprogs efibootmgr \
	    ethtool grub-pc grub-pc-bin grub-common grub2-common \
	    kmod libc-bin libicu52 libgpod-common libmtp-runtime \
	    libnetpbm10 libparted0debian1 libpci3 libpng12-0 mount netpbm \
	    ncurses-bin parted pcmciautils reiserfsprogs rsync sysvinit-utils \
	    udev udisks udpcast util-linux uuid-dev uuid-runtime xserver-xorg-input-vmmouse \
	    zlib1g zlib1g-dev \
	    libreadline6 libtinfo5 e2fslibs libcomerr2 \
	    libblkid1 libpcre3 libmount1 liblzma5 libpopt0 libacl1 libncurses5 libattr1 \
	    libkmod2  libdevmapper1.02.1 libdevmapper-dev libdevmapper-event1.02.1 libselinux1

#FIXME: Abhängigkeiten durch debootstrap auflösen
SYS32ARCHIVES= 

SYS64ARCHIVES=

DIRS := $(CACHEDIR)

# targets
all: build

$(DIRS):
	mkdir -p $(DIRS)

download: | $(DIRS)
	cd $(CACHEDIR); apt-get download $(addsuffix :i386, $(BIN_DEBS)) $(addsuffix :i386, $(BIN32_DEBS)) $(addsuffix :all, $(ALL_DEBS)) \
					$(addsuffix :amd64, $(BIN_DEBS)) $(addsuffix :amd64, $(BIN64_DEBS))
	rm -rf $(addprefix $(SYSROOT)/usr/share/doc/, $(BIN_DEBS) $(BIN32_DEBS) $(ALL_DEBS))
	rm -rf $(addprefix $(SYSROOT64)/usr/share/doc/, $(BIN_DEBS) $(BIN64_DEBS) $(ALL_DEBS))

configure: configure32 configure64

configure32: $(addprefix $(SYSROOT)/usr/share/doc/, $(BIN_DEBS) $(BIN32_DEBS) $(ALL_DEBS))

$(addprefix $(SYSROOT)/usr/share/doc/, $(BIN_DEBS) $(BIN32_DEBS) $(ALL_DEBS)): $(SYS32ARCHIVES)
	echo "[1mInstalling 32bit packages to sysroot...[0m"
	$(foreach pkg, $(wildcard $(CACHEDIR)/*_i386.deb) $(wildcard $(CACHEDIR)/*_all.deb), dpkg -x $(pkg) $(SYSROOT) ; )
	touch $(addprefix $(SYSROOT)/usr/share/doc/, $(BIN_DEBS) $(BIN32_DEBS) $(ALL_DEBS))

configure64: $(addprefix $(SYSROOT64)/usr/share/doc/, $(BIN_DEBS) $(BIN64_DEBS) $(ALL_DEBS))

$(addprefix $(SYSROOT64)/usr/share/doc/, $(BIN_DEBS) $(BIN64_DEBS) $(ALL_DEBS)): $(SYS64ARCHIVES)
	echo "[1mInstalling 64bit packages to sysroot...[0m"
	$(foreach pkg, $(wildcard $(CACHEDIR)/*_amd64.deb) $(wildcard $(CACHEDIR)/*_all.deb), dpkg -x $(pkg) $(SYSROOT64) ; )
	touch $(addprefix $(SYSROOT64)/usr/share/doc/, $(BIN_DEBS) $(BIN64_DEBS) $(ALL_DEBS))

build:

distclean: clean

clean: 

install:

.PHONY: all $(DIRS)
.PHONY: download build distclean clean install
.PHONY: configure configure32 configure64
