#!/bin/bash

HERE=`pwd`
QT_ARCHIVE=`grep qt- ../debian/md5sums.src | awk '{ print $2 }'`
export QTDIR="$HERE"/`echo "$QT_ARCHIVE" | sed -e 's/.tar.gz//'`
export QTLIB=$QTDIR/lib/
export QTBIN=$QTDIR/bin/ 

"$QTBIN"/qmake -makefile -spec "$QTDIR"/mkspecs/default linboGUI.pro

make clean
make
strip linbo_gui
