#!/bin/bash
#
# $Id$

error(){
 echo "$1"
 exit 1
}

[ -n "$LINBODIR" ] || error "LINBODIR not set."
[ -n "$INTERFACE" ] || error "INTERFACE not set."
[ -n "$MINCLIENTS" ] || error "MINCLIENTS not set."
[ -n "$MINSECONDS" ] || error "MINSECONDS not set."
[ -n "$MAXSECONDS" ] || error "MAXSECONDS not set."

cd "$LINBODIR" || exit 1

while read file serverport relax; do
 port="${serverport##*:}"
 if [ -s "$file" ]; then
  echo -n " * $file -> $INTERFACE:$port" >&2
  LOGFILE="$LINBODIR/log/${file}_mcast.log"
  while true; do
   echo >> $LOGFILE
   echo "### Starting new session: `date`" >> $LOGFILE
   udp-sender --full-duplex --interface "$INTERFACE" --portbase $port --min-clients $MINCLIENTS --min-wait $MINSECONDS --max-wait $MAXSECONDS --file "$file" --nokbd 2>> $LOGFILE 1>> $LOGFILE || exit 1
  done &
  echo .
 fi
done < multicast.list

