#!/bin/bash

### BEGIN INIT INFO
# Provides:          linbo-multicast
# Required-Start:    $network $local_fs
# Required-Stop:     $network $local_fs
# Should-Start:      
# Should-Stop:       
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start linbo multicast server
# Description:       Start linbo multicast server
### END INIT INFO

# Author: Thomas Schmitt <schmitt@lmz-bw.de>
# License: GPL V3
# $Id$

# defaults
LINBODIR=/var/linbo
START_MULTICAST=no
PORTBASE=9000
MINCLIENTS=16
MINSECONDS=60
MAXSECONDS=90
MULTICASTLIST=$LINBODIR/multicast.list
INTERFACE=eth0
SERVERIP=10.16.1.1

# read necessary functions and constants
. /usr/share/linuxmuster-linbo/helperfunctions.sh || exit 1
[ -f /etc/default/linuxmuster-linbo ] && . /etc/default/linuxmuster-linbo
[ "$START_MULTICAST" = "yes" -o ! -x /usr/sbin/linbo-multicast-server ] || exit 0
[ -e /usr/share/linuxmuster/config/dist.conf ] && . /usr/share/linuxmuster/config/dist.conf
. /lib/lsb/init-functions

# reading internal interface name
if [ -s /etc/default/linuxmuster-base ]; then
 . /etc/default/linuxmuster-base
 [ -n "$IFACE" ] && INTERFACE=$IFACE
fi

# reading server ip
[ -f /var/lib/linuxmuster/network.settings ] && . /var/lib/linuxmuster/network.settings && SERVERIP=$serverip

create_multicast_list() {
  echo -n "Creating multicast.list"
  [ -e "$MULTICASTLIST" ] && mv $MULTICASTLIST $MULTICASTLIST.old
  p=$PORTBASE
  for i in $images; do
    echo "$i $SERVERIP:$p" >> $MULTICASTLIST
    let "p+=2"
  done
  echo .
}

start() {
  images="$(active_images)"
  if [ -z "$images" ]; then
   echo "There exist no images yet!"
   rm -f "$MULTICASTLIST"
   exit 0
  fi
  create_multicast_list
  cd $LINBODIR
  echo "Starting linbo-multicast:" >&2
  LINBODIR=$LINBODIR INTERFACE=$INTERFACE MINCLIENTS=$MINCLIENTS MINSECONDS=$MINSECONDS MAXSECONDS=$MAXSECONDS /usr/sbin/linbo-multicast-server
}

stop() {
  echo -n "Stopping linbo-multicast" >&2
  killall linbo-multicast-server >/dev/null 2>&1
  killall udp-sender >/dev/null 2>&1
  echo .
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0
