#!/bin/bash
# Author: Thomas Schmitt <schmitt@lmz-bw.de>
# License: GPL V2
#
# /etc/init.d/starting linbo multicast server

# defaults
LINBODIR=/var/linbo
START_MULTICAST=no
PORTBASE=9000
MINCLIENTS=16
MINSECONDS=60
MAXSECONDS=90
MULTICASTLIST=$LINBODIR/multicast.list
INTERFACE=eth0
SERVERIP=10.16.1.1
LOGFILE=/var/log/linuxmuster/linbo_multicast.log

# reading linbo defaults
[ -f /etc/default/linuxmuster-linbo ] && . /etc/default/linuxmuster-linbo
[ "$START_MULTICAST" = "yes" -o ! -x /usr/sbin/linbo-multicast-server ] || exit 0

# reading internal interface name
[ -f /etc/default/linuxmuster-base ] && . /etc/default/linuxmuster-base && INTERFACE=$IFACE

# reading server ip
[ -f /var/lib/linuxmuster/network.settings ] && . /var/lib/linuxmuster/network.settings && SERVERIP=$serverip

create_multicast_list() {

	echo "Creating multicast.list ..."
	mv $MULTICASTLIST $MULTICASTLIST.old
	p=$PORTBASE
	BASEIMAGES=`grep ^BaseImage $LINBODIR/start.conf.* | awk -F= '{ print $2 }' | awk '{ print $1 }' | sort -u`
	IMAGES=`grep ^Image $LINBODIR/start.conf.* | awk -F= '{ print $2 }' | awk '{ print $1 }' | sort -u`
	for i in $BASEIMAGES $IMAGES; do
		if [ -s "$LINBODIR/$i" ]; then
			echo "$i $SERVERIP:$p" >> $MULTICASTLIST
			let "p+=2"
		fi
	done

}

start() {

	create_multicast_list
	cd $LINBODIR
	echo "Starting linbo multicast" >&2
	LINBODIR=$LINBODIR LOGFILE=$LOGFILE INTERFACE=$INTERFACE MINCLIENTS=$MINCLIENTS MINSECONDS=$MINSECONDS MAXSECONDS=$MAXSECONDS /usr/sbin/linbo-multicast-server

}

stop() {

	echo "Stopping linbo multicast" >&2
	killall linbo-multicast-server >/dev/null 2>&1
	killall udp-sender >/dev/null 2>&1

}


case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0
