#!/bin/bash
#
# postinst script for linuxmuster-linbo7
# thomas@linuxmuster.net
# GPL v3
# 20161025
#

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package
#

# Source debconf library.
#. /usr/share/debconf/confmodule

#db_version 2.0


case "$1" in

 configure)

  # read constants & setup values
    DISTCONF=/usr/share/linuxmuster/config/dist.conf
    source "$DISTCONF"
    source "$HELPERFUNCTIONS"
    [ -e "$INSTALLED" ] || exit 0

    update-linbofs
 
 # init script
 update-rc.d linbo-multicast defaults
 update-rc.d linbo-bittorrent defaults

 if [ -e "$DISTCONF" ]; then
  . $DISTCONF
  . $HELPERFUNCTIONS
  [ -e "$INSTALLED" ] || exit 0
 else
  exit 0
 fi

 # config file backup dir
 mkdir -p "$LINBODIR/backup"
 # windows activation stuff
 mkdir -p "$LINBODIR/winact"
 # additional torrents
 mkdir -p "$LINBODIR/torrentadds"
 # temp dir
 mkdir -p "$LINBODIR/tmp"

 # update serverip in start.conf
 echo "Setting server ip in start.conf.default."
 sed -e "s/^[Ss][Ee][Rr][Vv][Ee][Rr] = \([0-9]\{1,3\}[.]\)\{3\}[0-9]\{1,3\}/Server = $serverip/" -i "$LINBODIR/start.conf"

 # start.confs update
 if ls $LINBODIR/start.conf.* &> /dev/null; then

  # iterate over hostgroups
  for i in $(grep -i ^[a-z0-9] /etc/linuxmuster/workstations | awk -F\; '{ print $3 }' | sort -u); do
   conf="$LINBODIR/start.conf.$i"
   [ -e "$conf" ] || continue
   # add new KernelOptions option
   if ! grep -wqi ^kerneloptions "$conf"; then
    echo "Adding KernelOptions to start.conf.$i."
    if [ -s "$PXECFGDIR/$i" ]; then
     kopts="$(grep -i ^append "$PXECFGDIR/$i" | grep -i initrd=linbofs.lz | grep -i quiet | tail -1 | sed -e "s|append ||I" -e "s|splash||I" -e "s|initrd=linbofs.lz||I" -e "s|quiet||I" -e "s|vga=788||I" -e 's/^ *//g' -e 's/ *$//g')"
    else
     kopts=""
    fi
    cp -f "$conf" "$LINBODIR/backup"
    sed -e "/^\[[Ll][Ii][Nn][Bb][Oo]\]/a\
KernelOptions = $kopts" -i "$conf"
   fi
   # add new SystemType option
   if ! grep -wqi ^systemtype "$conf"; then
    echo "Adding SystemType to start.conf.$i."
    cp -f "$conf" "$LINBODIR/backup"
    sed -e "/^\[[Ll][Ii][Nn][Bb][Oo]\]/a\
SystemType = bios" -i "$conf"
   fi
  done
 fi

 # remove linbo logmail wrapper from /etc/aliases
 pattern="mail2log.sh"
 if grep -q "$pattern" /etc/aliases; then
  echo "Removing linbo's mail2log entry from /etc/aliases."
  cp /etc/aliases /etc/aliases.dpkg-old
  sed "/$pattern/d" /etc/aliases.dpkg-old > /etc/aliases
  newaliases
 fi

 # create bittorrent system user if necessary
 if ! grep -qw ^bittorrent /etc/passwd; then
  useradd -r -g nogroup -c "BitTorrent User" -d /var/lib/bittorrent -s /bin/false bittorrent
 fi

 # provide a bittorrent default file if necessary
 if [ ! -s /etc/default/bittorrent -a -s /usr/share/doc/bittorrent/examples/bittorrent.default ]; then
  cp /usr/share/doc/bittorrent/examples/bittorrent.default /etc/default/bittorrent
 fi

 # provide a bittorrent init script if necessary
 if [ ! -s /etc/init.d/bittorrent -a -s /usr/share/doc/bittorrent/examples/bittorrent.init ]; then
  cp /usr/share/doc/bittorrent/examples/bittorrent.init /etc/init.d/bittorrent
  chmod 755 /etc/init.d/bittorrent
  update-rc.d bittorrent defaults
 fi

 # provide a bittorrent logrotate file if necessary
 if [ ! -s /etc/logrotate.d/bittorrent ] || ! grep -q "create 600 bittorrent" /etc/logrotate.d/bittorrent &> /dev/null; then
  cp /usr/share/linuxmuster-linbo/templates/bittorrent.logrotate.d /etc/logrotate.d/bittorrent
 fi
 [ -d /var/log/bittorrent ] || mkdir -p /var/log/bittorrent
 chown bittorrent /var/log/bittorrent -R

 # change owner of logdir to nobody
 [ -d "$LINBOLOGDIR" ] || mkdir -p $LINBOLOGDIR
 chown nobody $LINBOLOGDIR -R

 # create dropbear ssh keys
 if [ ! -s "$SYSCONFDIR/linbo/ssh_host_rsa_key" ]; then
  ssh-keygen -t rsa -N "" -f $SYSCONFDIR/linbo/ssh_host_rsa_key
  /usr/lib/dropbear/dropbearconvert openssh dropbear $SYSCONFDIR/linbo/ssh_host_rsa_key $SYSCONFDIR/linbo/dropbear_rsa_host_key
 fi
 if [ ! -s "$SYSCONFDIR/linbo/ssh_host_dsa_key" ]; then
  ssh-keygen -t dsa -N "" -f $SYSCONFDIR/linbo/ssh_host_dsa_key
  /usr/lib/dropbear/dropbearconvert openssh dropbear $SYSCONFDIR/linbo/ssh_host_dsa_key $SYSCONFDIR/linbo/dropbear_dss_host_key
 fi

 # kill obsolete btdownloadheadless processes from old versions
 if ps ax | grep -v grep | grep -q btdownloadheadless; then
  service linbo-bittorrent stop
  oldpids="$(ps ax | grep -v grep | grep btdownloadheadless | awk '{ print $1 }')"
  echo "Sending obsolete btdownloadheadless processes the TERM signal."
  kill $oldpids
  service linbo-bittorrent start
 fi

 # create tftpd configs if necessary
 conf="/etc/default/tftpd-hpa"
 if ! grep -q "$LINBODIR" "$conf"; then
  echo "Patching $conf."
  cp "$conf" "$conf".dpkg-bak
  sed -i "s|^TFTP_DIRECTORY=.*|TFTP_DIRECTORY=\"$LINBODIR\"|" "$conf"
  tftpd_restart=yes
 fi
 if [ -n "$tftpd_restart" ]; then
  service tftpd-hpa stop &> /dev/null
  service tftpd-hpa start
 fi

 # update rsyncd.conf
 conf=/etc/rsyncd.conf
 tpl="$LINBOTPLDIR/$(basename $conf)"
 if ! grep rsync-post-download.sh "$conf" &> /dev/null; then
  echo "Updating $conf."
  [ -e "$conf" ] && cp "$conf" "$conf.dpkg-bak"
  sed -e "s|@@linbodir@@|$LINBODIR|g" "$tpl" > "$conf"
  service rsync restart
 fi

 # remove ALLOWED_DIR from bittorrent config
 conf="/etc/default/bittorrent"
 if grep -q ^ALLOWED_DIR "$conf"; then
  echo "Removing ALLOWED_DIR from $conf."
  cp "$conf" "$conf.dpkg-bak"
  sed -e 's|^ALLOWED_DIR|#ALLOWED_DIR|g' -i "$conf"
  bt_restart=yes
 fi
 # add REANNOUNCE_INTERVAL to bittorrent config
 if ! grep -q ^REANNOUNCE_INTERVAL "$conf"; then
  echo "Adding REANNOUNCE_INTERVAL=60 to $conf."
  [ -z "$bt_restart" ] && cp "$conf" "$conf.dpkg-bak"
  echo "REANNOUNCE_INTERVAL=60" >> "$conf"
  bt_restart=yes
 fi
 if [ -n "$bt_restart" ]; then
  service bittorrent restart || true
 fi

 # remove deprecated iso files
 if [ -d "$LINBODIR/isos" ]; then
  [ -e "$LINBODIR/isos/linbo32.iso" ] && rm -f "$LINBODIR/isos/linbo32.iso"
  [ -e "$LINBODIR/isos/linbo64.iso" ] && rm -f "$LINBODIR/isos/linbo64.iso"
  check_empty_dir "$LINBODIR/isos" && rm -rf "$LINBODIR/isos"
 fi

 # provide grub menu background
 [ -e "$LINBODIR/icons/linbo_wallpaper.png" ] || ln -sf linbo_wallpaper_800x600.png "$LINBODIR/icons/linbo_wallpaper.png"
 [ -e "$LINBODIR/boot/grub/linbo_wallpaper.png" ] || ln -sf ../../icons/linbo_wallpaper_800x600.png "$LINBODIR/boot/grub/linbo_wallpaper.png"
 ln -sf ../../linbo_wallpaper.png "$LINBODIR/boot/grub/themes/linbo/linbo_wallpaper.png"
 ;;

 abort-upgrade|abort-remove|abort-deconfigure)

 ;;

 *)
	 echo "postinst called with unknown argument \`$1'" >&2
	 exit 1
 ;;

esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

#db_stop

exit 0
