#!/bin/bash
#
# postinst script for linuxmuster-base
# thomas@linuxmuster.net
# 04.10.2013
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package
#

# Source debconf library.
#. /usr/share/debconf/confmodule

#db_version 2.0


DISTCONF=/usr/share/linuxmuster/config/dist.conf
[ -d /usr/share/doc/ubuntu-keyring ] && UBUNTU=yes

case "$1" in

 configure)

  # init script
  update-rc.d linbo-multicast defaults
  update-rc.d linbo-bittorrent defaults

  # linuxmuster related stuff
  if [ -e "$DISTCONF" ]; then
   . $DISTCONF
   . $HELPERFUNCTIONS
   [ -e "$INSTALLED" ] || exit 0
   [ "$imaging" = "linbo" ] || exit 0
  else
   exit 0
  fi

  # check serverip in default start.confs
  for i in $LINBODEFAULTCONF $SYSCONFDIR/linbo/start.conf.default; do
   if ! grep ^Server $i | grep -q "$serverip"; then
    echo "Adjusting server ip in $i to $serverip ..."
    cp $i $i.dpkg-old
    sed -e "s/^Server = \([0-9]\{1,3\}[.]\)\{3\}[0-9]\{1,3\}/Server = $serverip/" -i $i
   fi
  done

 # check for linbo mail wrapper in /etc/aliases
 if ! grep -q ^linbo: /etc/aliases; then
  cp /etc/aliases /etc/aliases.dpkg-old
  sed -e "/^root:/a\
linbo: \"\|\/usr\/share\/linuxmuster-linbo\/mail2log.sh\"" -i /etc/aliases
  newaliases
 fi

 # create bittorrent system user if necessary
 if ! grep -qw ^bittorrent /etc/passwd; then
  useradd -r -g nogroup -c "BitTorrent User" -d /var/lib/bittorrent -s /bin/false bittorrent
 fi

 # provide a bittorrent default file if necessary
 if [ ! -s /etc/default/bittorrent -a -s /usr/share/doc/bittorrent/examples/bittorrent.default ]; then
  cp /usr/share/doc/bittorrent/examples/bittorrent.default /etc/default/bittorrent
 fi

 # provide a bittorrent init script if necessary
 if [ ! -s /etc/init.d/bittorrent -a -s /usr/share/doc/bittorrent/examples/bittorrent.init ]; then
  cp /usr/share/doc/bittorrent/examples/bittorrent.init /etc/init.d/bittorrent
  chmod 755 /etc/init.d/bittorrent
  update-rc.d bittorrent defaults
 fi

 # provide a bittorrent logrotate file if necessary
 if [ ! -s /etc/logrotate.d/bittorrent ] || ! grep -q "create 600 bittorrent" /etc/logrotate.d/bittorrent &> /dev/null; then
  cp /usr/share/linuxmuster-linbo/templates/bittorrent.logrotate.d /etc/logrotate.d/bittorrent
 fi
 [ -d /var/log/bittorrent ] || mkdir -p /var/log/bittorrent
 chown bittorrent /var/log/bittorrent -R

 # setting needed options in /etc/default/bittorrent
 if [ -s /etc/default/bittorrent ]; then
  if ! grep -q ^REANNOUNCE_INTERVAL /etc/default/bittorrent; then
   echo "Adding REANNOUNCE_INTERVAL=15 to /etc/default/bittorrent."
   cp /etc/default/bittorrent /etc/default/bittorrent.dpkg-old && bt_backup=yes
   echo >> /etc/default/bittorrent
   echo "# seconds downloaders should wait between reannouncements (default 1800)" >> /etc/default/bittorrent
   echo "# 15 seconds is recommended value for linuxmuster-linbo" >> /etc/default/bittorrent
   echo "REANNOUNCE_INTERVAL=15" >> /etc/default/bittorrent
  fi
  if ! grep -q ^"DAEMONUSER=bittorrent" /etc/default/bittorrent; then
   echo "Adding DAEMONUSER=bittorrent to /etc/default/bittorrent."
   [ -z "$bt_backup" ] && cp /etc/default/bittorrent /etc/default/bittorrent.dpkg-old && bt_backup=yes
   sed -e 's|^DAEMONUSER=|#DAEMONUSER=|' -i /etc/default/bittorrent
   echo >> /etc/default/bittorrent
   echo "# it is recommended for linuxmuster-linbo to run the service as bittorrent user" >> /etc/default/bittorrent
   echo "DAEMONUSER=bittorrent" >> /etc/default/bittorrent
  fi
  if ! grep -q ^"ALLOWED_DIR=$LINBODIR" /etc/default/bittorrent; then
   echo "Adding ALLOWED_DIR=$LINBODIR to /etc/default/bittorrent."
   [ -z "$bt_backup" ] && cp /etc/default/bittorrent /etc/default/bittorrent.dpkg-old && bt_backup=yes
   sed -e 's|^ALLOWED_DIR=|#ALLOWED_DIR=|' -i /etc/default/bittorrent
   echo >> /etc/default/bittorrent
   echo "# where the LINBO images live" >> /etc/default/bittorrent
   echo "ALLOWED_DIR=$LINBODIR" >> /etc/default/bittorrent
  fi
  if ! grep -q ^"PORT=6969" /etc/default/bittorrent; then
   echo "Adding PORT=6969 to /etc/default/bittorrent."
   [ -z "$bt_backup" ] && cp /etc/default/bittorrent /etc/default/bittorrent.dpkg-old
   sed -e 's|^PORT=|#PORT=|' -i /etc/default/bittorrent
   echo >> /etc/default/bittorrent
   echo "# port must be 6969 for linuxmuster-linbo" >> /etc/default/bittorrent
   echo "PORT=6969" >> /etc/default/bittorrent
  fi
  # provide a logrotate file for bittorrent
  if [ ! -e /etc/logrotate.d/bittorrent ]; then
   echo "Creating /etc/logrotate.d/bittorrent."
   sed -e 's|/var/log/linuxmuster/linbo/|/var/log/bittorrent/|' /etc/logrotate.d/linuxmuster-linbo > /etc/logrotate.d/bittorrent
  fi
 fi # /etc/default/bittorrent

 # change owner of logdir to nobody
 [ -d "$LINBOLOGDIR" ] || mkdir -p $LINBOLOGDIR
 chown nobody $LINBOLOGDIR -R

 # create dropbear ssh keys
 if [ ! -s "$SYSCONFDIR/linbo/ssh_host_rsa_key" ]; then
  ssh-keygen -t rsa -N "" -f $SYSCONFDIR/linbo/ssh_host_rsa_key
  /usr/lib/dropbear/dropbearconvert openssh dropbear $SYSCONFDIR/linbo/ssh_host_rsa_key $SYSCONFDIR/linbo/dropbear_rsa_host_key
 fi
 if [ ! -s "$SYSCONFDIR/linbo/ssh_host_dsa_key" ]; then
  ssh-keygen -t dsa -N "" -f $SYSCONFDIR/linbo/ssh_host_dsa_key
  /usr/lib/dropbear/dropbearconvert openssh dropbear $SYSCONFDIR/linbo/ssh_host_dsa_key $SYSCONFDIR/linbo/dropbear_dss_host_key
 fi

 # kill obsolete btdownloadheadless processes from old versions
 if ps ax | grep -v grep | grep -q btdownloadheadless; then
  /etc/init.d/linbo-bittorrent stop
  oldpids="$(ps ax | grep -v grep | grep btdownloadheadless | awk '{ print $1 }')"
  echo "Sending obsolete btdownloadheadless processes the TERM signal."
  kill $oldpids
  /etc/init.d/linbo-bittorrent start
 fi

 # create tftpd-hpa configs if necessary
 conf="/etc/default/tftpd-hpa"
 if [ -n "$UBUNTU" ]; then
  tpl="$LINBOTPLDIR/tftpd-hpa.default.ubuntu"
  grep -q ubuntu "$conf" || update_config=yes
 else
  tpl="$LINBOTPLDIR/tftpd-hpa.default"
  grep -q openML "$conf" || update_config=yes
 fi
 grep -q "$LINBODIR" "$conf" || update_config=yes
 if [ -n "$update_config" ]; then
  echo "Patching $conf."
  cp "$conf" "$conf".dpkg-bak
  sed -e "s|@@linbodir@@|$LINBODIR|" "$tpl" > "$conf"
  tftpd_restart=yes
 fi
 conf="/etc/tftp_remap.conf"
 tpl="$LINBOTPLDIR/$(basename $conf)"
 if [ ! -e "$conf" ]; then
  echo "Providing $conf."
  cp "$tpl" "$conf"
  tftpd_restart=yes
 fi
 if [ -n "$tftpd_restart" ]; then
  # check for tftp in inetd.conf
  if grep -q ^tftp /etc/inetd.conf; then
   echo "Deactivating tftp in /etc/inetd.conf."
   cp /etc/inetd.conf /etc/inetd.conf.dpkg-bak
   sed -e 's|^tftp|#tftp|' -i /etc/inetd.conf
   /etc/init.d/openbsd-inetd restart
  fi
  if [ -n "$UBUNTU" ]; then
   restart tftpd-hpa
  else
   /etc/init.d/tftpd-hpa restart
  fi
 fi

 # update rsyncd.conf
 conf=/etc/rsyncd.conf
 tpl="$LINBOTPLDIR/$(basename $conf)"
 if ! grep rsync-pre-download.sh "$conf" &> /dev/null; then
  echo "Updating $conf."
  [ -e "$conf" ] && cp "$conf" "$conf.dpkg-bak"
  sed -e "s|@@linbodir@@|$LINBODIR|g" "$tpl" > "$conf"
  /etc/init.d/rsync restart
 fi

 # update linbofs.gz
 $LINBOUPDATE
 ;;

 abort-upgrade|abort-remove|abort-deconfigure)

 ;;

 *)
	 echo "postinst called with unknown argument \`$1'" >&2
	 exit 1
 ;;

esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

#db_stop

exit 0

