#!/bin/bash
#
# preinst script for linuxmuster-base
# thomas@linuxmuster.net
# 02.07.2013
#

if [ "$1" = "upgrade" ]; then

 . /usr/share/linuxmuster/config/dist.conf || exit 1

 # stopping multicast before package configuration
 [ -x /etc/init.d/linbo-multicast ] && /etc/init.d/linbo-multicast stop

 # add bittorrent user if not present
 if ! id bittorrent &> /dev/null; then
  adduser --gecos "BitTorrent User" --home /var/lib/bittorrent --ingroup nogroup --system bittorrent
  dpkg-statoverride --add bittorrent nogroup 755 /var/lib/bittorrent || true
  dpkg-statoverride --add bittorrent nogroup 755 /var/log/bittorrent || true
  chown bittorrent:nogroup /var/lib/bittorrent -R
  chown bittorrent:nogroup /var/log/bittorrent -R
 fi

 # move deprecated syslinux stuff away
 pxebkpdir="$LINBODIR/backup/pxelinux"
 for i in boot.msg german.kbd logo.16 memdisk pxelinux.0 pxelinux.cfg vesamenu.c32; do
  if [ -e "$LINBODIR/$i" ]; then
   [ -d "$pxebkpdir" ] || mkdir -p "$pxebkpdir"
   mv "$LINBODIR/$i" "$pxebkpdir"
  fi
 done

fi

exit 0

