#!/bin/sh -e
#
# $Id$

if [ "$1" = "upgrade" ]; then

 . /usr/share/linuxmuster/config/dist.conf || exit 1

 # stopping multicast before package configuration
 [ -x /etc/init.d/linbo-multicast ] && /etc/init.d/linbo-multicast stop

 # saving default pxe config if it is not yet a link
 [ -L "$PXELINUXCFG" ] || cp "$PXELINUXCFG" "$PXELINUXCFG.dpkg-bak"

fi

exit 0

