#!/bin/bash

# Build QT embedded. This can be painful...

QT_ARCHIVE=`grep qt- ../debian/md5sums.src | awk '{ print $2 }'`
export QTDIR=`pwd`/`echo "$QT_ARCHIVE" | sed -e 's/.tar.gz//'`
cd $QTDIR

export CXX=g++-4.3
echo -e "yes\n" | ./configure \
 -embedded x86 \
 -prefix $QTDIR \
 -opensource \
 -release \
 -static \
 -no-accessibility \
 -no-xmlpatterns \
 -no-phonon \
 -no-phonon-backend \
 -no-webkit \
 -no-exceptions \
 -no-svg \
 -no-scripttools \
 -no-nis \
 -no-cups \
 -no-stl \
 -verbose \
 -qt-zlib \
 -qt-libpng \
 -no-gif \
 -no-libjpeg \
 -no-openssl \
 -no-iconv \
 -no-dbus \
 -depths 4,8,16 \
 -no-largefile \
 -no-xinerama \
 -no-xrender \
 -no-freetype \
 -qt-gfx-linuxfb \
 -no-gfx-vnc \
 -no-gfx-multiscreen \
 -no-gfx-transformed \
 -no-gfx-qvfb \
 -no-opengl \
 -no-glib \
 -no-libmng \
 -qt-decoration-default \
 -no-decoration-windows \
 -no-decoration-styled \
 -nomake examples \
 -nomake demos \
 -no-qdbus \
 -no-sm \
 -no-xrender \
 -no-libtiff \
 -no-xkb \
 -no-xshape \
 -no-xrandr \
 -no-xfixes \
 -no-xinput \
 -no-declarative-debug \
 -no-audio-backend \
 -no-javascript-jit \
 -no-script \
 -no-multimedia
 
cd $QTDIR
make -j 4
