#!/bin/bash

HERE=`pwd`
export QTDIR=$HERE/qt-embedded-linux-opensource-src-4.5.2
export QTLIB=$QTDIR/lib/
export QTBIN=$QTDIR/bin/ 

$HERE/qt-embedded-linux-opensource-src-4.5.2/bin/qmake -makefile -spec qt-embedded-linux-opensource-src-4.5.2/mkspecs/default linboGUI.pro

make clean
make CXX=g++-4.3
strip linbo_gui
