#!/bin/bash

# Build QT embedded. This can be painful...

SRCDIR=qt-embedded-free-3.3.7

( cd $SRCDIR
  export QTDIR=`pwd`
  export CXX=g++-4.1
  echo -e "yes\n" | ./configure -embedded x86 -prefix /usr -release -static -no-ipv6 -disable-network -disable-opengl -disable-sql -no-exceptions -no-nis -no-cups -no-stl -verbose -no-gif -depths 4,8,16 -no-kbd-sl5000 -no-kbd-yopy -no-kbd-vr41xx -no-mouse-yopy -no-mouse-vr41xx -no-largefile -no-style-cde -no-style-compact -no-style-motif -no-style-motifplus -no-style-platinum -no-style-sgi -no-xinerama -no-xrender -no-xft -no-freetype -qt-gfx-vga16
  make sub-src )
